export * from '$utils/converters/base64'
export * from '$utils/converters/bytes'
export * from '$utils/data-structures/arrToMap'
export * from '$utils/data-structures/arrToRecord'
export * from '$utils/dimensional/countries'
export * from '$utils/navigator/getCountry'
export * from '$utils/navigator/getTimezone'
export * from '$utils/navigator/getOperatingSystem'
export * from '$utils/navigator/isSupported'
export * from '$utils/number/clamp'
export * from '$utils/parsers/phone'
export * from '$utils/text/capitalize'
export * from '$utils/validation/email'

// const version = 'Utilities Common v0.1.0'
// export default version
